### ISSUE TITLE
[BUG] Could not pass event WorldLoadEvent

### ISSUE THREAD

**Issue by andris155** [OpticFusion1/Slimefun-Reloaded#14]
## General Troubleshooting
  
- [x] I have checked for similar issues.
- [x] I have updated to the latest version.
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

**Describe the bug**

**To Reproduce**
Start 1.15.1 server with Slimefun-reloaded

**Expected behavior**
No write this error.

**Screenshots**

**Additional context**
```
[15:00:58 INFO]: [SlimefunReloaded] Loading Blocks for World "world115"
[15:00:58 INFO]: [SlimefunReloaded] This may take a long time...
[15:00:58 INFO]: [SlimefunReloaded] Loading Blocks... 100% (FINISHED - 0ms)
[15:00:58 INFO]: [SlimefunReloaded] Loaded a total of 0 Blocks for World "world115"
[15:00:58 ERROR]: Could not pass event WorldLoadEvent to SlimefunReloaded v0.0.1
java.lang.NullPointerException: null
at optic_fusion1.slimefunreloaded.util.BlockStorage.<init>(BlockStorage.java:181) ~[?:?]
at optic_fusion1.slimefunreloaded.util.BlockStorage.getForcedStorage(BlockStorage.java:53) ~[?:?]
at optic_fusion1.slimefunreloaded.listener.WorldListener.on(WorldListener.java:19) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor49.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-25]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.createWorld(CraftServer.java:1023) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.Bukkit.createWorld(Bukkit.java:492) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.WorldCreator.createWorld(WorldCreator.java:284) ~[patched_1.15.1.jar:git-Paper-25]
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-25]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-25]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-25]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-25]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-25]
at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by OpticFusion1** [comment]
I've fixed this error actually, and similar ones. Issue is #13 needs fixed first before i can release an update .-.
